---
- name: play to experiment with network modules and devices
  hosts: network
  gather_subset: config
  tasks:
   - name: print the device config to confirm that fact gathering is using the correct module
     debug: 
        msg: "{{ ansible_facts['net_config'] }}"
   - name: use the ping module to see that it works with network devices 
     ping: 
      data: "NotPong"
   - name: use the vyos ping module to ping serversfrom vyos node
     vyos_ping:
       dest: "{{ item }}"
       count: 1
     loop:
      - servera
      - serverb
      - serverc
      - serverd

   - name: Backup the configuration
     vyos_config:
       backup: true
       backup_options:
         dir_path: "{{ playbook_dir }}/backup"
         filename: vyos-config-latest

   - name: run a basic command
     vyos_command: 
        commands:
         - show version
 #    debug:
  #        msg: "{{The command output is ['show version'] }}"

