---

- name: unsafe strings demo
  hosts: localhost
  vars_prompt:
   - name: unsafe_string
     prompt: provide some data
     private: False
 
  tasks: 
   - name: create a file containing the user input
     copy:
       content: "{{unsafe_string}}"
       dest: /tmp/demofile
